/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-05-19 08:50:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ask_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1649033184895L));
    _jspx_dependants.put("jar:file:/D:/workspace-ddadaLast/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddada/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace-ddadaLast/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddada/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>ASK</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.rawgit.com/moonspam/NanumSquare/master/nanumsquare.css\" /> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- content start -->   \r\n");
      out.write("      <div class=\"col\" >\r\n");
      out.write("      \r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("\r\n");
      out.write("            <h1>1:1고객문의</h1>\r\n");
      out.write("                <hr>\r\n");
      out.write("                       <div>\r\n");
      out.write("                                <h2>고객 한분 한분의 목소리에도 귀 기울이겠습니다</h2>\r\n");
      out.write("                                \r\n");
      out.write("                                <br>\r\n");
      out.write("                                \r\n");
      out.write("                                <blockquote>\r\n");
      out.write("                                <P style=\"text-align:left\">\r\n");
      out.write("                                    *수강중인 강의 관련자료는 홈페이지 내 수강관리  – 해당강좌 페이지에서 다운로드\r\n");
      out.write("                                    가능합니다. <br />\r\n");
      out.write("                                    * 환급관련 업무는 Ddada (대표번호:7942-7942)로 문의 주시기 바랍니다.<br /><br />\r\n");
      out.write("                                </p>\r\n");
      out.write("                                </blockquote>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <strong><p style=\"text-align:left\">개인정보의 수집 및 이용에 관한 동의</p></strong>\r\n");
      out.write("                        <p style=\"text-align:left\">\r\n");
      out.write("                        1. Ddada 홈페이지는 고객 문의사항 처리를 위하여 아래와 같이 개인정보를 수집ㆍ이용 합니다. <br /><br />\r\n");
      out.write("                        개인정보 수집ㆍ이용 내역 <br />\r\n");
      out.write("                                <table class=\"table_01\" width=\"100%\" style = \"width : 886px; border : 1px solid #bcbcbc;\">\r\n");
      out.write("                                    <!-- <caption class=\"blind\">\r\n");
      out.write("                                        수집항목,수집 및 이용목적,보유 및 이용기간 -->\r\n");
      out.write("                                    </caption>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <tr style = \"border-bottom : 1px solid #bcbcbc; background-color : #cde9ff\">\r\n");
      out.write("                                        <th style = \"border-right : 1px solid #bcbcbc; padding-left : 20px;\">수집항목</th>\r\n");
      out.write("                                        <th style = \"border-right : 1px solid #bcbcbc; padding-left : 20px;\">수집 및 이용목적</th>\r\n");
      out.write("                              			<th style = \"padding-left : 20px;\">보유 및 이용기간</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td style = \"border-right : 1px solid #bcbcbc; padding-left : 20px;\"align=\"left\">이메일주소</td>\r\n");
      out.write("                                        <td style = \"border-right : 1px solid #bcbcbc; padding-top : 11px; padding-left : 20px;\"align=\"left\"><strong><u>고객 문의사항 처리</u></strong></p>\r\n");
      out.write("                              			<td style = \"padding-top : 11px; padding-left : 20px;\"align=\"left\"><strong><u>목적 달성 즉시 파기</u></strong></p>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                </table>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <p  style=\"text-align:left\">\r\n");
      out.write("                        위의 개인정보 수집ㆍ이용에 대한 동의를 거부할 권리가 있습니다.<br>\r\n");
      out.write("                        그러나 동의를 거부할 경우 문의사항에 대한 답변이 제한될 수 있습니다\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        2. Ddada 홈페이지는 만 14세 미만 정보주체의 개인정보를 처리하지 않으므로 만 14세 미만의 아동은 1:1문의를 할 수 없습니다.\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                           <input type=\"checkbox\" id=\"ckva1\" name=\"ckva1\" v-model=\"ckva_1\" style=\"width:20px\"> &nbsp; 본인은 만 14세 이상 입니다.\r\n");
      out.write("                        <br>\r\n");
      out.write("                           <input type=\"checkbox\" id=\"ckva2\" name=\"ckva2\" v-model=\"ckva_2\" style=\"width:20px\"> &nbsp; 위와 같이 개인정보를 수집ㆍ이용하는데 동의합니다.\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        \r\n");
      out.write("                        <br>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                      </div>\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"clear\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"con\">\r\n");
      out.write("                                <table class=\"table_01\">\r\n");
      out.write("                                    <caption class=\"blind\">\r\n");
      out.write("                                        이메일, 분류선택, 제목, 내용입력으로 구성된 1:1 고객문의 등록\r\n");
      out.write("                                    </caption>\r\n");
      out.write("                                    <colgroup>\r\n");
      out.write("                                        <col width=\"100px\" />\r\n");
      out.write("                                        <col width=\"600px\" />\r\n");
      out.write("                                    </colgroup>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <tr class=\"block1\" style=\"display: none;\">\r\n");
      out.write("                                        <th scope=\"row\" title=\"성명\">ㆍ성명</th>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <input type=\"text\" id=\"txtName\" name=\"txtName\" style=\"width:200px;\" v-model=\"name\" title=\"성명\" />\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <tr class=\"block2\">\r\n");
      out.write("                                        <th scope=\"row\">ㆍ이메일</th>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            \r\n");
      out.write("                                                <input type=\"text\" id=\"txtEmail1\" name=\"txtEmail1\"  title=\"이메일 아이디 (직접 입력)\" />&nbsp;@&nbsp;\r\n");
      out.write("                                                <input type=\"text\" id=\"txtEmail2\" name=\"txtEmail2\" title=\"이메일 도메인 주소 (직접 입력)\" />\r\n");
      out.write("                                            \r\n");
      out.write("                                            \r\n");
      out.write("                                                <select id=\"ddlEmail\" name=\"ddlEmail\" title=\"이메일 도메인 주소 (선택 입력)\" class=\"styled\" onChange=\"f_email(); return false;\">\r\n");
      out.write("                                                    <option selected=\"selected\" value=\"직접입력\">직접입력</option>\r\n");
      out.write("                                                    <option value=\"nate.com\">nate.com</option>\r\n");
      out.write("                                                    <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("                                                    <option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("                                                    <option value=\"daum.net\">daum.net</option>\r\n");
      out.write("                                                    <option value=\"hotmail.com\">hotmail.com</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <tr class=\"block4\">\r\n");
      out.write("                                        <th scope=\"row\">ㆍ분류선택</th>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            \r\n");
      out.write("                                                <select id=\"ddlType\" class=\"styled\" style=\"width:300px;\" v-model=\"type\" title=\"분류 선택\">\r\n");
      out.write("                                                    <option value=\"\" selected>선택</option>\r\n");
      out.write("                                                    <!-- <option v-for=\"(val,key) in _types.qnaTypesKOR\" v-bind:key=\"key\" v-bind:value=\"key\">{{val}}</option> -->\r\n");
      out.write("                                                    <option value=\"A001\">강좌 관련</option>\r\n");
      out.write("                                                    <option value=\"A001\">환불 관련</option>\r\n");
      out.write("                                                    <option value=\"A001\">기타</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                    <tr class=\"block5\">\r\n");
      out.write("                                        <th scope=\"row\">ㆍ제목</th>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <input type=\"text\" id=\"txtTitle\" name=\"txtTitle\" v-model=\"title\" title=\"제목\" style=\"width:99%;\" />\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr class=\"enter\">\r\n");
      out.write("                                        <th scope=\"row\">ㆍ내용입력</th>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <textarea id=\"txtContents\" name=\"txtContents\" rows=\"20\" cols=\"20\" style=\"width:99%;\" v-model=\"contents\" title=\"내용 입력\" ></textarea>\r\n");
      out.write("                                            * 문의 내용 기재 시 성함, 연락처, 소속 등의 개인 정보는 기재하지 말아주시기 바랍니다.\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                           \r\n");
      out.write("                            <div class=\"btn_area\" align=\"center\">\r\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/ask2.do\" class=\"qna_btn\" v-on:click.stop.prevent=\"save()\">\r\n");
      out.write("						          <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\"\r\n");
      out.write("						                  style=\"border-color: black; background-color: rgb(186, 222, 248); color: black;\">\r\n");
      out.write("						                  등록</button>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("               </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/ask.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/board/ask.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/ask.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
