/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-05-16 07:14:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class certificateInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1649033184895L));
    _jspx_dependants.put("jar:file:/D:/workspace-ddadaLast/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddada/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace-ddadaLast/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ddada/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

  request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/a62f32303e.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("   <title>자격증 정보</title>\r\n");
      out.write("\r\n");
      out.write("   <style>\r\n");
      out.write("      .certificate{\r\n");
      out.write("      text-align : left;\r\n");
      out.write("      }\r\n");
      out.write("      .sqldinfo{\r\n");
      out.write("      text-align : center;\r\n");
      out.write("      float : relative;\r\n");
      out.write("      margin-left : 300px;\r\n");
      out.write("      }\r\n");
      out.write("      #informationCerti1{\r\n");
      out.write("      margin-left : 266px;\r\n");
      out.write("      }\r\n");
      out.write("      #informationCerti2{\r\n");
      out.write("      margin-left : 151px;\r\n");
      out.write("      }\r\n");
      out.write("      #informationMS1{\r\n");
      out.write("      margin-left : 373px;\r\n");
      out.write("      }\r\n");
      out.write("      #informationMS2{\r\n");
      out.write("      margin-left : 208px;\r\n");
      out.write("      }\r\n");
      out.write("      #networkInfo{\r\n");
      out.write("      margin-left : 287px;\r\n");
      out.write("      }\r\n");
      out.write("      .likebutton{\r\n");
      out.write("      margin-left : 300px;\r\n");
      out.write("      }\r\n");
      out.write("      .writebutton{\r\n");
      out.write("      margin-left : 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .container {\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        margin: 2px auto;\r\n");
      out.write("        text-align:left;\r\n");
      out.write("        border: 1px solid #bcbcbc;\r\n");
      out.write("        float : relative;\r\n");
      out.write("        border-radius : 15px 15px 15px 15px;\r\n");
      out.write("         }\r\n");
      out.write("        h2{\r\n");
      out.write("        width : 80%;\r\n");
      out.write("        margin : 2px;\r\n");
      out.write("        }\r\n");
      out.write("   </style>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("      function counterSqld(){\r\n");
      out.write("         var dday = new Date(\"2022.05.28\").getTime(); //디데이\r\n");
      out.write("         setInterval(function(){\r\n");
      out.write("            var now = new Date(); //현재 날짜 가져오기\r\n");
      out.write("            var distance = dday - now;\r\n");
      out.write("            var d = Math.floor(distance / (1000 * 60 * 60 * 24));\r\n");
      out.write("            $('#ddaySqld').text(\"D-\"+d)\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      counterSqld();\r\n");
      out.write("      function counterProgramming(){\r\n");
      out.write("         var dday = new Date(\"2022.07.02\").getTime(); //디데이\r\n");
      out.write("         setInterval(function(){\r\n");
      out.write("            var now = new Date(); //현재 날짜 가져오기\r\n");
      out.write("            var distance = dday - now;\r\n");
      out.write("            var d = Math.floor(distance / (1000 * 60 * 60 * 24));\r\n");
      out.write("            $('#ddayProgramming').text(\"D-\"+d)\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("      counterProgramming();\r\n");
      out.write("      function counterLinux(){\r\n");
      out.write("         var dday = new Date(\"2022.07.26\").getTime(); //디데이\r\n");
      out.write("         setInterval(function(){\r\n");
      out.write("            var now = new Date(); //현재 날짜 가져오기\r\n");
      out.write("            var distance = dday - now;\r\n");
      out.write("            var d = Math.floor(distance / (1000 * 60 * 60 * 24));\r\n");
      out.write("            $('#ddayLinux').text(\"D-\"+d)\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("      counterLinux();\r\n");
      out.write("      function counterNetwork(){\r\n");
      out.write("         var dday = new Date(\"2022.08.21\").getTime(); //디데이\r\n");
      out.write("         setInterval(function(){\r\n");
      out.write("            var now = new Date(); //현재 날짜 가져오기\r\n");
      out.write("            var distance = dday - now;\r\n");
      out.write("            var d = Math.floor(distance / (1000 * 60 * 60 * 24));\r\n");
      out.write("            $('#ddayNetwork').text(\"D-\"+d)\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("      counterNetwork();\r\n");
      out.write("      function counterInformationSecure(){\r\n");
      out.write("         var dday = new Date(\"2022.06.25\").getTime(); //디데이\r\n");
      out.write("         setInterval(function(){\r\n");
      out.write("            var now = new Date(); //현재 날짜 가져오기\r\n");
      out.write("            var distance = dday - now;\r\n");
      out.write("            var d = Math.floor(distance / (1000 * 60 * 60 * 24));\r\n");
      out.write("            $('#ddayInformationSecure').text(\"D-\"+d)\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("      counterInformationSecure();\r\n");
      out.write("      function counterInformationManagement(){\r\n");
      out.write("         var dday = new Date(\"2022.07.02\").getTime(); //디데이\r\n");
      out.write("         setInterval(function(){\r\n");
      out.write("            var now = new Date(); //현재 날짜 가져오기\r\n");
      out.write("            var distance = dday - now;\r\n");
      out.write("            var d = Math.floor(distance / (1000 * 60 * 60 * 24));\r\n");
      out.write("            $('#ddayInformationManagement').text(\"D-\"+d)\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("      counterInformationManagement();\r\n");
      out.write("   </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("     <div class = \"certificate\">\r\n");
      out.write("      <!-- <h3 style=\"line-height:50px;\">자격증 > </h3> -->\r\n");
      out.write("      <br>\r\n");
      out.write("      <h3 class=\"myDD_category\" style=\"text-align:left;\"> 자격증 ></h3>\r\n");
      out.write("      <br>\r\n");
      out.write("        <select name = \"certi\" id = \"certi\" style = \"width : 200px;\">\r\n");
      out.write("           <option value = \"\" selected = \"selected\">분야선택</option>\r\n");
      out.write("           <option value = \"Programming\">정보기술</option>\r\n");
      out.write("           <option value = \"OS\" >OS</option>\r\n");
      out.write("           <option value = \"Network\">네트워크</option>\r\n");
      out.write("           <option value = \"Secure\">해킹&정보보안</option>\r\n");
      out.write("           <option value = \"Database\">데이터베이스</option>\r\n");
      out.write("           <option value = \"Cloud\">클라우드</option>\r\n");
      out.write("           <option value = \"etc\">기타</option>\r\n");
      out.write("        </select>\r\n");
      out.write("     </div>\r\n");
      out.write("    <div class=\"container\" id = \"sqld\" style = \"float : left; margin-top:10px;\">\r\n");
      out.write("         <table  class = \"Database\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/sqld.do\" class=\"card-link\">SQLD(P)</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                    <span class=\"badge badge-light\" id = \"ddaySqld\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 데이터베이스 <span class = \"sqldinfo\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;접수기간 : 05.02(월)~05.06(금)</span></h6><br>\r\n");
      out.write("            <h6>시험일 : 2022.05.28(토) <span class = \"sqldinfo\"><a href=\"https://www.dataq.or.kr/www/main.do\" class=\"card-link\" target=\"_blank\"><u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>시험시간 : 10:00 ~ 11:30 <span class = \"sqldinfo\"> <a href=\"https://quizeey.com/sqlp-developer\" class=\"card-link\" target=\"_blank\"><u>기출문제(링크클릭)</u></a></span>\r\n");
      out.write("            <span class = \"linkButton\">\r\n");
      out.write("               <span class = \"likebutton unchecked\" id = likeBut>\r\n");
      out.write("                  <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("                  <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\" id = \"informationProcessing\" style = \"float : left; margin-top:20px;\">\r\n");
      out.write("         <table  class = \"Programming\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/informationProcessing.do\" class=\"card-link\">정보처리기사</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                    <span class=\"badge badge-light\" id = \"ddayProgramming\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 정보기술 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class = \"sqldinfo\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;접수기간 : 06.07(월)10:00 ~ 06.10(목)18:00</span></h6><br>\r\n");
      out.write("            <h6>필기시험일 : 2022.07.02(일) <span id = \"informationCerti1\"><a href=\"https://www.q-net.or.kr/rcv001.do?id=rcv00103&gSite=&gId=\" class=\"card-link\" target=\"_blank\">&nbsp;&nbsp;<u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>실기시험일 : 2022.09.03(토)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span id = \"informationCerti2\"> <a href=\"https://www.comcbt.com/xe/iz\" class=\"card-link\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>기출문제(링크클릭)</u></a>\r\n");
      out.write("            <span class = \"linkButton\">\r\n");
      out.write("               <span class = \"likebutton\">\r\n");
      out.write("                  <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("                  <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"container\" id = \"MSAzure\" style = \"float : left; margin-top:20px;\">\r\n");
      out.write("         <table  class = \"Cloud\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/MSAzure.do\" class=\"card-link\">MS Azure</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; margin-top : 5px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                    <span class=\"badge badge-light\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\">상시접수</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 클라우드 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class = \"sqldinfo\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;접수기간 : 상시</span></h6><br>\r\n");
      out.write("            <h6>응시료 : $69 <span id = \"informationMS1\"><a href=\"https://docs.microsoft.com/ko-kr/learn/certifications/exams/az-900\" class=\"card-link\" target=\"_blank\">&nbsp;&nbsp;<u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>시험 시간 : 60분, 합격점 : 700/1000점 &nbsp;<span id = \"informationMS2\"> <a href=\"https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWSRk3\" class=\"card-link\" target=\"_blank\"><u>기출문제(링크클릭)</u></a>\r\n");
      out.write("            <span class = \"likebutton\">\r\n");
      out.write("               <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("               <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"container\" id = \"networkManage\"style = \"float : left; margin-top:20px;\">\r\n");
      out.write("         <table  class = \"Network\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/networkManagement.do\" class=\"card-link\">네트워크 관리사</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                   <span class=\"badge badge-light\" id = \"ddayNetwork\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 네트워크&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class = \"sqldinfo\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;접수기간 : 2022.07.19(화) ~ 2022.07.22(금)</span></h6><br>\r\n");
      out.write("            <h6>필기시험일 : 2022.08.21(일)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span id = \"informationMS2\"><a href=\"https://www.icqa.or.kr/cn/\" class=\"card-link\" target=\"_blank\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>실기시험일 : 2022.09.25(일)<span style = \"margin-left : 281px;\" id = \"informationMS2\"> <a href=\"https://www.icqa.or.kr/cn/board/dataroom\" class=\"card-link\" target=\"_blank\"><u>기출문제(링크클릭)</u></a>\r\n");
      out.write("            <span class = \"likebutton\">\r\n");
      out.write("               <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("               <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\" id = \"linux\" style = \"float : left; margin-top:20px;\">\r\n");
      out.write("         <table  class = \"OS\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/linuxMaster.do\" class=\"card-link\">리눅스 마스터</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                   <span class=\"badge badge-light\" id = \"ddayLinux\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 운영체제&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class = \"sqldinfo\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;접수기간 : 2022.07.25(월) ~ 2022.08.03(수)</span></h6><br>\r\n");
      out.write("            <h6>1차시험일 : 2022.7.26(일)<span style = \"margin-left : 300px;\" id = \"informationMS2\"><a href=\"https://www.ihd.or.kr/introducesubject1.do\" class=\"card-link\" target=\"_blank\"><u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>2차시험일 : 2022.9.03(토)<span style = \"margin-left : 294px;\"id = \"informationMS2\"> <a href=\"https://www.comcbt.com/xe/r2\" class=\"card-link\" target=\"_blank\"><u>기출문제(링크클릭)</u></a>\r\n");
      out.write("            <span class = \"likebutton\">\r\n");
      out.write("               <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("               <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\" id = \"informationSecure\" style = \"float : left; margin-top:20px;\">\r\n");
      out.write("         <table  class = \"Secure\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/informationSecure.do\" class=\"card-link\">정보보안 산업기사</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                   <span class=\"badge badge-light\" id = \"ddayInformationSecure\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 정보보안 <span style = \"margin-left : 370px;\" class = \"sqldinfo\">접수기간 : 2022.05.31(화) ~ 2022.06.03(금)</span></h6><br>\r\n");
      out.write("            <h6>필기시험일 : 2022.06.25(토)<span style = \"margin-left : 280px;\"><a href=\"https://www.cq.or.kr/qh_quagm05_001.do\" class=\"card-link\" target=\"_blank\"><u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>실기시험일 : 2022.08.13(토)<span style = \"margin-left : 281px;\"> <a href=\"https://www.q-net.or.kr/cst006.do?id=cst00601&code=1203&gSite=&gId=\" class=\"card-link\" target=\"_blank\"><u>기출문제(링크클릭)</u></a>\r\n");
      out.write("            <span class = \"likebutton\">\r\n");
      out.write("               <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("               <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\" id = \"informationManage\" style = \"float : left; margin-top:20px;\">\r\n");
      out.write("         <table  class = \"Programming\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/informationManage.do\" class=\"card-link\">정보관리기술사</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                   <span class=\"badge badge-light\" id = \"ddayInformationManagement\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 정보기술 <span style = \"margin-left : 370px;\">접수기간 : 2022.06.08(수) ~ 2022.06.13(월)</span></h6><br>\r\n");
      out.write("            <h6>필기시험일 : 2022.07.02(토)<span style = \"margin-left : 280px;\"><a href=\"https://www.q-net.or.kr/rcv001.do?id=rcv00103&gSite=&gId=\" class=\"card-link\" target=\"_blank\"><u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>실기시험일 : 2022.10.01(토)<span style = \"margin-left : 281px;\"> <a href=\"https://q.fran.kr/%EC%8B%9C%ED%97%98/%EC%A0%95%EB%B3%B4%EA%B4%80%EB%A6%AC%EA%B8%B0%EC%88%A0%EC%82%AC\" class=\"card-link\" target=\"_blank\"><u>기출문제(링크클릭)</u></a>\r\n");
      out.write("            <span class = \"likebutton\">\r\n");
      out.write("               <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("               <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\" id = \"comUse\" style = \"float : left; margin-top:20px;\">\r\n");
      out.write("         <table  class = \"etc\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/computerUse.do\" class=\"card-link\">컴퓨터활용능력</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                   <span class=\"badge badge-light\" id = \"ddayNetwork\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\">상시접수</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 기타 <span style = \"margin-left : 395px;\">접수기간 : 상시가능</span></h6><br>\r\n");
      out.write("            <h6>필기시험일 : 매주 주말<span style = \"margin-left : 331px;\"><a href=\"https://license.korcham.net/indexmain.jsp\" class=\"card-link\" target=\"_blank\"><u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>실기시험일 : 매주 주말<span style = \"margin-left : 328px;\"> <a href=\"https://license.korcham.net/co/examguide02.do?cd=0103&mm=21\" class=\"card-link\" target=\"_blank\"><u>기출문제(링크클릭)</u></a>\r\n");
      out.write("            <span class = \"likebutton\">\r\n");
      out.write("               <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("               <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"container\" id = \"word\" style = \"float : left; margin-top:20px;\">\r\n");
      out.write("         <table  class = \"etc\">\r\n");
      out.write("        <tr>\r\n");
      out.write("           <td style = \"width : 1100px;\">\r\n");
      out.write("            <h2><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/word.do\" class=\"card-link\">워드프로세서</a>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" style=\"font-size:medium; background-color: rgba(255, 255, 255, 255);\r\n");
      out.write("                  margin: 0px; padding: 0px; box-shadow: none;\">\r\n");
      out.write("                   <span class=\"badge badge-light\" id = \"ddayNetwork\" style=\"padding-top:0px; padding-bottom:0px; margin-top: 5px; color:rgb(255, 40, 40);\">상시접수</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                </h2>\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <h6>분류 : 기타 <span style = \"margin-left : 395px;\">접수기간 : 상시가능</span></h6><br>\r\n");
      out.write("            <h6>필기시험일 : 매주 주말<span style = \"margin-left : 331px;\"><a href=\"https://license.korcham.net/indexmain.jsp\" class=\"card-link\" target=\"_blank\"><u>접수하기(링크클릭)</u></a></span></h6><br>\r\n");
      out.write("            <h6>실기시험일 : 매주 주말<span style = \"margin-left : 328px;\"> <a href=\"https://license.korcham.net/co/examguide02.do?cd=0102&mm=22\" class=\"card-link\" target=\"_blank\"><u>기출문제(링크클릭)</u></a>\r\n");
      out.write("            <span class = \"likebutton\">\r\n");
      out.write("               <i class=\"fa-regular fa-heart\"></i>\r\n");
      out.write("               <span class = \"writebutton\">\r\n");
      out.write("               <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("               </span>\r\n");
      out.write("            </span>\r\n");
      out.write("            </span></h6>\r\n");
      out.write("           </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("<script>\r\n");
      out.write("   $(\"#certi option:selected\").val();\r\n");
      out.write("   $(\"select[name=certi]\").val();\r\n");
      out.write("   $(\"#certi option\").index($(\"#certi option:selected\"));\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("        $('#certi').change(function() {\r\n");
      out.write("          var result = $('#certi option:selected').val();\r\n");
      out.write("          if (result == 'Programming') {\r\n");
      out.write("             $('#informationProcessing, #informationManage').show();\r\n");
      out.write("            $('#comUse, #word, #sqld, #MSAzure, #networkManage, #linux, #informationSecure, #amazon').hide();\r\n");
      out.write("          }\r\n");
      out.write("          else if (result == 'Database') {\r\n");
      out.write("            $('#sqld').show();\r\n");
      out.write("            $('#comUse, #word, #informationProcessing, #MSAzure, #networkManage, #linux, #informationSecure, #amazon, #informationManage').hide();\r\n");
      out.write("          }\r\n");
      out.write("          else if (result == 'Cloud') {\r\n");
      out.write("           $('#MSAzure,#amazon').show();\r\n");
      out.write("           $('#comUse, #word, #sqld, #informationProcessing, #networkManage, #linux, #informationSecure, #informationManage').hide();\r\n");
      out.write("         }\r\n");
      out.write("          else if (result == 'Network') {\r\n");
      out.write("           $('#networkManage').show();\r\n");
      out.write("           $('#comUse, #word, #sqld, #informationProcessing, #MSAzure, #linux, #informationSecure, #amazon, #informationManage').hide();\r\n");
      out.write("         }\r\n");
      out.write("          else if (result == 'OS') {\r\n");
      out.write("              $('#linux').show();\r\n");
      out.write("              $('#comUse, #word, #sqld, #informationProcessing, #MSAzure, #networkManage, #informationSecure, #amazon, #informationManage').hide();\r\n");
      out.write("         }\r\n");
      out.write("          else if (result == 'Secure') {\r\n");
      out.write("              $('#informationSecure').show();\r\n");
      out.write("              $('#comUse, #word, #sqld, #informationProcessing, #MSAzure, #networkManage, #linux, #amazon, #informationManage').hide();\r\n");
      out.write("         }\r\n");
      out.write("          else if (result == '') {\r\n");
      out.write("              $('#informationSecure, #comUse, #word, #sqld, #informationProcessing, #MSAzure, #networkManage, #linux, #amazon, #informationManage').show();\r\n");
      out.write("         }\r\n");
      out.write("          else{\r\n");
      out.write("            $('#comUse, #word').show();\r\n");
      out.write("            $('#sqld, #informationProcessing, #MSAzure, #networkManage, #linux, #informationSecure, #amazon, #informationManage').hide();\r\n");
      out.write("          }\r\n");
      out.write("        }); \r\n");
      out.write("      });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/certificateInfo.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/board/certificateInfo.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/certificateInfo.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
